[package]
name = "spark-rs"
version = "0.3.0"
authors = ["Erwin Kroon <erwin@k3n.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
itertools = "^0.10.5"
clap = "^4.0.29"
