[package]
name = "spark-rs"
version = "0.1.1-dev"
authors = ["Erwin Kroon <erwin@k3n.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
itertools = "^0.10.3"
clap = "^3.0.9"
