[package]
name = "spark-rs"
version = "0.1.0"
authors = ["Erwin Kroon <erwin@k3n.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
itertools = "0.9.0"
clap = "3.0.0-beta.1"
