name: Test and build spark

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
   
  release-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v1
      with: 
        name: spark
        path: target/release/spark
      
  release-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v1
      with: 
        name: spark
        path: target/release/spark
        
  release-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v1
      with: 
        name: spark
        path: target/release/spark
